(function(g){var window=this;'use strict';var Ejb=function(a,b){if(!Number.isFinite(a))return String(a);a=String(a);var c=a.indexOf(".");-1===c&&(c=a.length);var d="-"===a[0]?"-":"";d&&(a=a.substring(1));return d+(0,g.Aab)("0",Math.max(0,b-c))+a},Fjb=function(){return{G:"svg",
Y:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},X:[{G:"path",Y:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.64-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.63 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2z"}}]}},Gjb=function(){return{G:"svg",
Y:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},X:[{G:"path",Y:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.63-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.64 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2zm-2 1H8v-6c0-2.48 1.51-4.5 4-4.5s4 2.02 4 4.5v6z"}}]}},Ijb=function(a){"number"===typeof a?(this.date=Hjb(a,0,1),A6(this,1)):g.Za(a)?(this.date=Hjb(a.getFullYear(),a.getMonth(),a.getDate()),A6(this,a.getDate())):(this.date=new Date(g.eb()),a=this.date.getDate(),
this.date.setHours(0),this.date.setMinutes(0),this.date.setSeconds(0),this.date.setMilliseconds(0),A6(this,a))},Hjb=function(a,b,c){b=new Date(a,b,c);
0<=a&&100>a&&b.setFullYear(b.getFullYear()-1900);return b},A6=function(a,b){a.getDate()!=b&&a.date.setUTCHours(a.date.getUTCHours()+(a.getDate()<b?1:-1))},B6=function(a,b){g.aT.call(this,a,{G:"div",
S:"ytp-reminder-menu",Y:{role:"menu",tabindex:"-1"},X:[{G:"div",S:"ytp-reminder-menu-contents",X:[{G:"div",S:"ytp-reminder-menu-items"}]}]},100,!0);this.buttonElement=b;this.j=[];this.menuPopupRenderer=void 0;this.items=this.Ha("ytp-reminder-menu-items");this.hide()},Kjb=function(a){var b=Jjb(a),c=0,d={};
for(c=0;c<b.length;d={EJ:d.EJ},c++){var e=a.j[c];e||(e=new g.X({G:"div",S:"ytp-reminder-menu-item",Y:{role:"menuitem",tabindex:"0"},X:[{G:"div",S:"ytp-reminder-menu-item-icon",ya:"{{icon}}"},{G:"div",S:"ytp-reminder-menu-item-label",ya:"{{text}}"}]}),d.EJ=c,e.Ta("click",function(l){return function(){var m=l.EJ;a.Mb();m=Jjb(a)[m];a.ra("reminderMenuItemClicked",m.serviceEndpoint||m.command)}}(d)),e.Ja(a.items),a.j[c]=e);
var f=b[c],h=null;switch(f.icon&&f.icon.iconType){case "NOTIFICATIONS":h=Fjb();break;case "NOTIFICATIONS_NONE":h=Gjb();break;case "NOTIFICATIONS_ACTIVE":h=g.UEa()}f=f.text?g.PG(f.text):"";e.update({icon:h,text:f})}for(;c<a.j.length;)a.j.pop().dispose();0===c?a.Mb():a.xd(a.buttonElement)},Jjb=function(a){return(a.menuPopupRenderer&&a.menuPopupRenderer.items||[]).reduce(function(b,c){c&&c.menuServiceItemRenderer&&b.push(c.menuServiceItemRenderer);
return b},[])},C6=function(a){g.X.call(this,{G:"div",
X:[{G:"button",Na:["ytp-offline-slate-button","ytp-button"],X:[{G:"div",S:"ytp-offline-slate-button-icon",ya:"{{icon}}"},{G:"div",S:"ytp-offline-slate-button-text",ya:"{{text}}"}]}]});this.I=a;this.upcomingEventReminderButtonRenderer=this.toggleButtonRenderer=null;this.u=void 0;this.C=this.j=null;(this.buttonElement=this.Ha("ytp-offline-slate-button"))&&this.T(this.buttonElement,"click",this.D);this.hide()},Mjb=function(a,b,c){!a.toggleButtonRenderer&&b&&b.toggleButtonRenderer?a.toggleButtonRenderer=
b.toggleButtonRenderer:b&&b.toggleButtonRenderer||(a.toggleButtonRenderer=null);
!a.upcomingEventReminderButtonRenderer&&c&&g.S(c,Ljb)?a.upcomingEventReminderButtonRenderer=g.S(c,Ljb):c&&g.S(c,Ljb)||(a.upcomingEventReminderButtonRenderer=null);D6(a)},D6=function(a){if(a.toggleButtonRenderer){var b=a.toggleButtonRenderer;
if(b.isToggled){var c=b.toggledText?g.PG(b.toggledText):"";a.update({text:c,icon:Njb(b.toggledIcon)})}else c=b.defaultText?g.PG(b.defaultText):"",a.update({text:c,icon:Njb(b.defaultIcon)});a.show()}else a.upcomingEventReminderButtonRenderer?(b=Ojb(a))?(c=b.text?g.PG(b.text):"",a.update({text:c,icon:Njb(b.icon)}),a.show()):a.hide():a.hide()},Qjb=function(a,b,c){a.C||(a.C=new g.BD(a.I.W().yl));
var d={context:g.YC(a.C.config_||g.XC())};g.mH()&&(d.context.clientScreenNonce=g.mH());d.params=c;g.CD(a.C,b,d,{timeout:5E3,onSuccess:function(){a.upcomingEventReminderButtonRenderer&&a.u&&(a.upcomingEventReminderButtonRenderer.currentState=a.u,a.u=void 0)},
onError:function(){Pjb(a)},
onTimeout:function(){Pjb(a)}})},Pjb=function(a){a.toggleButtonRenderer?(a.toggleButtonRenderer.isToggled=!a.toggleButtonRenderer.isToggled,D6(a)):a.upcomingEventReminderButtonRenderer&&(a.u=void 0,D6(a))},Njb=function(a){if(!a)return null;
switch(a.iconType){case "NOTIFICATIONS":return Fjb();case "NOTIFICATIONS_NONE":return Gjb();case "NOTIFICATIONS_ACTIVE":return g.UEa();default:return null}},Ojb=function(a){if(!a.upcomingEventReminderButtonRenderer)return null;
var b=a.u||a.upcomingEventReminderButtonRenderer.currentState;a=g.u(a.upcomingEventReminderButtonRenderer.states||[]);for(var c=a.next();!c.done;c=a.next())if((c=g.S(c.value,Rjb))&&c.state===b&&c.button&&g.S(c.button,g.qO))return g.S(c.button,g.qO);return null},Sjb=function(a){g.X.call(this,{G:"div",
S:"ytp-offline-slate",X:[{G:"div",S:"ytp-offline-slate-background"},{G:"div",S:"ytp-offline-slate-bar",X:[{G:"span",S:"ytp-offline-slate-icon",X:[{G:"svg",Y:{fill:"#fff",height:"100%",viewBox:"0 0 24 24",width:"100%"},X:[{G:"path",Y:{d:"M16.94 6.91l-1.41 1.45c.9.94 1.46 2.22 1.46 3.64s-.56 2.71-1.46 3.64l1.41 1.45c1.27-1.31 2.05-3.11 2.05-5.09s-.78-3.79-2.05-5.09zM19.77 4l-1.41 1.45C19.98 7.13 21 9.44 21 12.01c0 2.57-1.01 4.88-2.64 6.54l1.4 1.45c2.01-2.04 3.24-4.87 3.24-7.99 0-3.13-1.23-5.96-3.23-8.01zM7.06 6.91c-1.27 1.3-2.05 3.1-2.05 5.09s.78 3.79 2.05 5.09l1.41-1.45c-.9-.94-1.46-2.22-1.46-3.64s.56-2.71 1.46-3.64L7.06 6.91zM5.64 5.45L4.24 4C2.23 6.04 1 8.87 1 11.99c0 3.13 1.23 5.96 3.23 8.01l1.41-1.45C4.02 16.87 3 14.56 3 11.99s1.01-4.88 2.64-6.54z"}},
{G:"circle",Y:{cx:"12",cy:"12",r:"3"}}]}]},{G:"span",S:"ytp-offline-slate-messages",X:[{G:"div",S:"ytp-offline-slate-main-text",Y:{"aria-label":"{{label}}"},ya:"{{mainText}}"},{G:"div",S:"ytp-offline-slate-subtitle-text",ya:"{{subtitleText}}"}]},{G:"span",S:"ytp-offline-slate-buttons"}]},{G:"button",Na:["ytp-offline-slate-close-button","ytp-button"],X:[g.fR()]},{G:"button",Na:["ytp-offline-slate-open-button","ytp-button"],X:[g.eR()]}]});var b=this;this.api=a;this.j=this.u=null;this.background=this.Ha("ytp-offline-slate-background");
this.B=this.Ha("ytp-offline-slate-bar");this.D=new g.Dq(function(){g.Lq(b.B,"ytp-offline-slate-bar-fade")},15E3);
this.J=!1;this.C=new g.Dq(function(){g.Lq(b.element,"ytp-offline-slate-collapsed")},15E3);
g.H(this,this.C);g.H(this,this.D);this.countdownTimer=new g.Dq(this.YZ,1E3,this);this.T(a,"presentingplayerstatechange",this.b_);this.T(a,"livestatedata",this.Sa);a=this.Ha("ytp-offline-slate-close-button");this.T(a,"click",function(){g.Lq(b.element,"ytp-offline-slate-collapsed")});
a=this.Ha("ytp-offline-slate-open-button");this.T(a,"click",function(){g.Nq(b.element,"ytp-offline-slate-collapsed")});
this.hide();a=this.getVideoData();a.getPlayerResponse()&&(a=a.getPlayerResponse().playabilityStatus)&&this.Sa(a);a=8===this.api.getPresentingPlayerType()&&!this.getVideoData().Ml;var c=8===this.api.getPresentingPlayerType();g.Pq(this.element,"ytp-offline-slate-premiere-trailer",a);g.Pq(this.element,"ytp-offline-slate-hide-background",c)},Tjb=function(a,b,c){if(b){var d=null!=b.subtitleText?g.PG(b.subtitleText):"";
c=c?c:null!=b.mainText?g.PG(b.mainText):"";var e,f,h,l;b=null!=(l=null==(e=b.mainText)?void 0:null==(f=e.accessibility)?void 0:null==(h=f.accessibilityData)?void 0:h.label)?l:c;a.update({mainText:c,subtitleText:d,label:b});g.Pq(a.element,"ytp-offline-slate-single-text-line",!d);g.Pq(a.B,"ytp-offline-slate-bar-hidden",!c&&!d)}},E6=function(a,b){var c=(0,g.gC)();
this.module="heartbeat";this.trigger=a;this.j=b;this.B=c},akb=function(a){g.XT.call(this,a);
var b=this;this.K=!1;this.V=0;this.D=!1;this.u=new g.Dq(function(){var e=b.player.W(),f=b.getVideoData();F6(b)&&(Ujb(b)?Vjb(b,e,f):(Wjb(b),Xjb(b,e,f)))},0);
this.j=this.heartbeatParams=null;this.C=!1;this.J=new g.uj(1E3,6E4,1);this.sequenceNumber=0;this.offlineSlate=null;this.oa=new g.BD(void 0);this.ea=this.attestationResponse=void 0;this.utcOffsetMinutes=-(new Ijb).getTimezoneOffset();this.B=new g.LK(this);g.H(this,this.u);g.H(this,this.B);Wjb(this);Yjb(this);this.B.T(a,"heartbeatparams",this.ID);this.B.T(a,"presentingplayerstatechange",this.C0);this.B.T(a,"videoplayerreset",this.D0);this.B.T(a,g.JG("heartbeat"),this.onCueRangeEnter);this.C&&this.j&&
Zjb(this,void 0,this.j);var c=new g.HG(1E3,0x7ffffffffffff,{priority:1,namespace:"heartbeat"}),d=new g.HG(0x8000000000000,0x8000000000000,{id:"stream_end",priority:1,namespace:"heartbeat"});a.hf([c,d]);$jb(this)},$jb=function(a){var b=a.getVideoData();
b.Dm&&(b=b.botguardData)&&g.OKa(b,a.player.W())},Wjb=function(a){var b=a.getVideoData();
if(b.Dm&&(b=new g.KKa(b),g.wS.isInitialized()||3<=a.sequenceNumber)){var c=null;if(b.videoData.Mk){var d=g.LKa(b);if(d){c={};var e={};d=d.split("&");d=g.u(d);for(var f=d.next();!f.done;f=d.next())f=f.value.split("="),2===f.length&&(e[f[0]]=f[1]);e.r1a&&(c.webResponse=e.r1a);e.r1c&&(c.error=bkb[Number(e.r1c)]);c.challenge=b.videoData.Mk}}a.attestationResponse=c||void 0}},Ujb=function(a){var b=a.getVideoData();
if(!g.AO(a.getVideoData())||b.vV)return!1;if(b.useInnertubeDrmService()&&b.D){a="playready"===b.D.flavor&&b.N("html5_innertube_heartbeats_for_playready");var c="widevine"===b.D.flavor&&b.N("html5_innertube_heartbeats_for_widevine");b=g.HL(b.D)&&b.N("html5_innertube_heartbeats_for_fairplay");return!(a||c||b)}return!0},ckb=function(a){if(Ujb(a))return!!a.heartbeatParams;
var b=a.getVideoData();return g.AO(a.getVideoData())&&b.useInnertubeDrmService()&&!b.yl&&!b.ZJ?!1:!!b.heartbeatToken},G6=function(a,b){if(!a.u.isActive()&&a.K){var c=a.getVideoData();
if(ckb(a)||c.isLivePlayback){if(void 0===b)if(a.D)if(a.C)b=7500;else{var d;b=(null==(d=a.heartbeatParams)?0:d.interval)?1E3*a.heartbeatParams.interval:a.getVideoData().AT||6E4}else b=1E3;a.u.start(b)}}},gkb=function(a,b,c){b.Nm&&(c=g.Sj(c,{internalipoverride:b.Nm}));
var d={cpn:b.clientPlaybackNonce};b.contextParams&&(d.context_params=b.contextParams);b.wb&&(d.kpt=b.wb);c=g.Sj(c,d);g.bA(c,{format:"RAW",method:"GET",timeout:3E4,onSuccess:function(e){if(!a.u.isActive()&&F6(a)){a.J.reset();a.sequenceNumber++;e=e.responseText;var f=dkb(e);if(f){a.player.Qa("onHeartbeat",f);var h="ok"===f.status?f.stop_heartbeat?2:0:"stop"===f.status?1:"live_stream_offline"===f.status?0:-1}else h=(h=e.match(ekb))?"0"===h[1]?0:1:-1;fkb(a,void 0,f,e,h)}},
onError:function(e){F6(a)&&H6(a,!0,"net-"+e.status)},
onTimeout:function(){F6(a)&&H6(a,!0,"timeout")},
withCredentials:!0})},Vjb=function(a,b,c){var d;
if(null!=(d=a.heartbeatParams)&&d.url){var e=g.Sj(a.heartbeatParams.url,{request_id:g.wra()});c.qa&&(e=g.Sj(e,{vvt:c.qa}),c.mdxEnvironment&&(e=g.Sj(e,{mdx_environment:c.mdxEnvironment})));g.ZM(b,c.oauthToken).then(function(f){f&&(e=g.Sj(e,{access_token:f}));gkb(a,c,e)})}},F6=function(a){var b=a.getVideoData();
return 3===a.player.getPresentingPlayerType()||g.zP(a.player.Nb(a.getPlayerType()),4)?!1:ckb(a)||b.isLivePlayback?!0:(I6(a),!1)},Xjb=function(a,b,c){var d,e={videoId:c.videoId,
sequenceNumber:a.sequenceNumber,heartbeatServerData:null!=(d=a.qa)?d:c.heartbeatServerData};a.ea=a.attestationResponse;c.Dm&&(e.attestationResponse=a.ea);var f=g.zS(c),h;d=null!=(h=f.client)?h:{};d.utcOffsetMinutes=a.utcOffsetMinutes;e.context=f;e.cpn=c.clientPlaybackNonce;if(h="undefined"!==typeof Intl?(new Intl.DateTimeFormat).resolvedOptions().timeZone:null)d.timeZone=h;h={heartbeatChecks:[]};if(d=c.getPlayerResponse())c.heartbeatToken&&(e.heartbeatToken=c.heartbeatToken),(d=d.playabilityStatus)&&
(d=d.liveStreamability)&&d.liveStreamabilityRenderer&&h.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_LIVE_STREAM_STATUS");c.heartbeatToken&&h.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_YPC");if(g.TM(b)){h.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_UNPLUGGED");f=hkb(a);d={};null!==f&&(d.clientPlayerPositionUtcMillis=f);var l,m;f=(null==(m=null==(l=a.player.Fb())?void 0:g.kU(l))?void 0:m.freePreviewWatchedDuration)||0;0<f&&(d.freePreviewWatchedDuration={seconds:""+f});h.unpluggedParams=d}e.heartbeatRequestParams=
h;c.isLivePlayback?(l=hkb(a),null!==l&&(e.playbackState||(e.playbackState={}),e.playbackState.playbackPosition={utcTimeMillis:l})):b.N("enable_heartbeat_vod_playback_position")&&(l=ikb(a),null!==l&&(e.playbackState||(e.playbackState={}),e.playbackState.playbackPosition={streamTimeMillis:l}));a.player.ra("heartbeatRequest",e);var n={timeout:3E4,onSuccess:function(p){if(!a.u.isActive()&&F6(a)){var q=a.getVideoData(),r=q.Dm&&null==a.ea,v;q.Dm=!(null==(v=p.heartbeatAttestationConfig)||!v.requiresAttestation)||
r;r=p.playabilityStatus;v=JSON.stringify(r)||"{}";p.authenticationMismatch&&a.player.Aa("authshear",{});var y=-1;var A=p.playabilityStatus;A&&(a.player.Qa("onHeartbeat",A),"OK"===A.status?y=p.stopHeartbeat?2:0:"UNPLAYABLE"===A.status?y=1:"LIVE_STREAM_OFFLINE"===A.status&&(y=0));a.sequenceNumber&&-1===y||a.J.reset();a.sequenceNumber++;p.heartbeatServerData&&(a.qa=p.heartbeatServerData);q.GK=p;(A=p.playerCueRangeSet)&&g.Yya(q,A);p.playerCueRanges&&0<p.playerCueRanges.length&&(q.cueRanges=p.playerCueRanges);
var F,L;(null==(F=p.progressBarConfig)?0:F.progressBarStartPosition)&&(null==(L=p.progressBarConfig)?0:L.progressBarEndPosition)&&(q.progressBarStartPosition=p.progressBarConfig.progressBarStartPosition,q.progressBarEndPosition=p.progressBarConfig.progressBarEndPosition);q.compositeLiveIngestionOffsetToken=p.compositeLiveIngestionOffsetToken;p.compositeLiveStatusToken!==q.compositeLiveStatusToken&&(q.compositeLiveStatusToken=p.compositeLiveStatusToken);q.ra("dataupdated");fkb(a,p,r,v,y)}},
onError:function(p){F6(a)&&H6(a,!0,"net-"+p.status)},
onTimeout:function(){F6(a)&&H6(a,!0,"timeout")}};
g.ZM(b,g.QO(c)).then(function(p){p&&(n.NT="Bearer "+p);g.CD(a.oa,"player/heartbeat",e,n)})},fkb=function(a,b,c,d,e){-1===e?(c="decode "+g.ig(d,3),H6(a,!1,c)):2===e?(I6(a),a.D=!0):(a.V=0,a.u.stop(),1===e?(a.D=!1,a.player.Zg("heartbeat.stop",2,a.Mf(d)),g.OB("heartbeatActionPlayerHalted",jkb(c)),a.player.N("html5_use_video_transition_endpoint_heartbeat")&&(null==b?0:b.videoTransitionEndpoint)&&c&&(b=b.videoTransitionEndpoint,(d=g.S(b,g.rO))&&kkb(a,d,c,{itct:null==b?void 0:b.clickTrackingParams}))):(a.D=
!0,d=0,a.C&&c&&(d=Zjb(a,b,c),a.player.ra("livestatedata",c)),d?G6(a,d):G6(a)))},Zjb=function(a,b,c){var d=c.liveStreamability&&c.liveStreamability.liveStreamabilityRenderer,e=!(!d||!(d.switchStreamsImmediately||d.transitionTiming&&"STREAM_TRANSITION_TIMING_IMMEDIATELY"===d.transitionTiming));
b=lkb(a,b,d);var f=a.getVideoData(),h=a.player.Nb(a.getPlayerType()),l=h.ud()&&!g.EO(f)&&!a.player.isAtLiveHead(a.getPlayerType());if(f.W().Hd()){var m,n=(null==(m=a.player.Qe())?void 0:m.qc())||{};n.status=c.status||"";n.dvr=""+ +l;n["switch"]=""+ +e;n.ended=""+ +!(!d||!d.displayEndscreen);a.player.Aa("heartbeat",n)}if(l&&!e)return b;e=d&&d.streamTransitionEndpoint&&g.S(d.streamTransitionEndpoint,g.rO);if("STREAM_TRANSITION_TIMING_AT_STREAM_END"===(d&&d.transitionTiming))a.getVideoData().transitionEndpointAtEndOfStream=
e;else if(e&&kkb(a,e,c))return b;if("OK"===c.status.toUpperCase()){e=d&&d.broadcastId;m=a.j&&a.j.liveStreamability&&a.j.liveStreamability.liveStreamabilityRenderer&&a.j.liveStreamability.liveStreamabilityRenderer.broadcastId;l=e!==m&&null!=e;if(!f.hlsvp&&!f.kb||l){var p={video_id:f.videoId};f.QK&&(p.is_live_destination="1");a.player.N("web_player_heartbeat_request_watch_next")||(p.disable_watch_next=!0,p.raw_watch_next_response=f.Ad);p.autonav_state=f.autonavState;p.oauth_token=f.oauthToken;p.force_gvi=
f.Mm;p.wm=f.wm;f.J&&(p.vss_credentials_token=f.J,p.vss_credentials_token_type=f.Fk);f.qa&&(p.vvt=f.qa);d=void 0;f.hlsvp||f.kb?l&&(d=new E6("broadcastIdChanged",m+","+e),a.DH("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_BROADCAST_ID_CHANGED",c)):(e&&(d=new E6("formatsReceived",""+e)),a.DH("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_LIVE_STREAM_WENT_ONLINE",c));a.player.loadVideoByPlayerVars(p,void 0,void 0,void 0,d);return b}a.player.Fg("heartbeat",
a.getPlayerType())}d&&d.displayEndscreen&&(a.offlineSlate?(a=a.offlineSlate,a.J=!0,a.Gb&&a.api.xA()):g.fQ(h)&&(f=(null==(p=a.player.Qe())?void 0:p.qc())||{},a.player.Aa("hbse",f,!0),a.player.xA(),a.player.Qa("onLiveMediaEnded",c)));return b},lkb=function(a,b,c){return a.player.N("web_player_use_heartbeat_poll_delay_ms")&&(a=Number(null==b?void 0:b.pollDelayMs))?a:(c=Number(null==c?void 0:c.pollDelayMs))?c:0},H6=function(a,b,c){var d=a.player.W();
if(!a.u.isActive()){a.u.stop();a.V++;var e=b?"heartbeat.net":"heartbeat.servererror";var f=a.getVideoData();if(f.iU||b&&!g.AO(a.getVideoData())&&!ckb(a)&&f.isLivePlayback)f=!1;else{var h,l;(null==(l=a.heartbeatParams)?0:l.pA)?h=a.heartbeatParams.pA:h=f.ST||5;f=a.V>=h}f?(g.OB("heartbeatActionPlayerHalted",b?{enforcedPolicyToHaltOnNetworkFailure:!0}:jkb()),(b=a.getVideoData())&&b.isLivePlayback?a.player.Zg(e,1,"Video playback interrupted. Please try again.",c):a.player.Zg(e,1,"Sorry, there was an error licensing this video.",
c)):(d.N("html5_report_non_fatal_heartbeat_error")&&a.player.Lr(e,{msg:c}),G6(a,a.J.getValue()),g.vj(a.J))}},jkb=function(a){var b={enforcedPolicyToHaltOnNetworkFailure:!1};
a&&(b.serializedServerContext=a.additionalLoggingData);return b},I6=function(a){a.V=0;
a.u.stop();a.D=!1;a.sequenceNumber=0},Yjb=function(a){var b=a.getVideoData(),c=a.player.W();
if(b.isLivePlayback)if(g.iwa(c.D)){a.C=!0;a.K=!0;if(!g.KM(c)||g.TM(c))a.offlineSlate=new Sjb(a.player),g.H(a,a.offlineSlate),g.YS(a.player,a.offlineSlate.element,4);(b=b.getPlayerResponse())&&b.playabilityStatus&&(a.j=b.playabilityStatus);var d;"UNPLAYABLE"!==(null==(d=a.j)?void 0:d.status)&&(a.j?(d=lkb(a,void 0,a.j.liveStreamability&&a.j.liveStreamability.liveStreamabilityRenderer))?G6(a,d):G6(a,7500):G6(a,1E3))}else a.player.Zg("html5.unsupportedlive",2,"HTML5_NO_AVAILABLE_FORMATS_FALLBACK","nolive.1");
else g.Hb(b.Fa,"heartbeat")&&a.player.Fg("heartbeat",a.getPlayerType())},kkb=function(a,b,c,d){var e=b&&b.videoId;
return e?(a.player.qo(e,Object.assign({},{autonav:"1"},d||{}),void 0,!0,!0,b,g.QO(a.getVideoData())),a.DH("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT",c),!0):!1},hkb=function(a){return(a=a.player.getProgressState(a.getPlayerType()).ingestionTime)&&isFinite(a)?""+Math.floor(1E3*a):null},ikb=function(a){return(a=a.player.getCurrentTime(a.getPlayerType()))&&isFinite(a)?""+Math.floor(1E3*a):null},dkb=function(a){try{var b=JSON.parse(a);
return null!=b?b:void 0}catch(c){}},mkb={ERAS:["BC",
"AD"],ERANAMES:["Before Christ","Anno Domini"],NARROWMONTHS:"JFMAMJJASOND".split(""),STANDALONENARROWMONTHS:"JFMAMJJASOND".split(""),MONTHS:"January February March April May June July August September October November December".split(" "),STANDALONEMONTHS:"January February March April May June July August September October November December".split(" "),SHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),STANDALONESHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),
WEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),STANDALONEWEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),SHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),STANDALONESHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),NARROWWEEKDAYS:"SMTWTFS".split(""),STANDALONENARROWWEEKDAYS:"SMTWTFS".split(""),SHORTQUARTERS:["Q1","Q2","Q3","Q4"],QUARTERS:["1st quarter","2nd quarter","3rd quarter","4th quarter"],AMPMS:["AM","PM"],DATEFORMATS:["EEEE, MMMM d, y",
"MMMM d, y","MMM d, y","M/d/yy"],TIMEFORMATS:["h:mm:ss\u202fa zzzz","h:mm:ss\u202fa z","h:mm:ss\u202fa","h:mm\u202fa"],DATETIMEFORMATS:["{1} 'at' {0}","{1} 'at' {0}","{1}, {0}","{1}, {0}"],FIRSTDAYOFWEEK:6,WEEKENDRANGE:[5,6],FIRSTWEEKCUTOFFDAY:5},nkb=mkb;nkb=mkb;var bkb=["ATTESTATION_ERROR_UNKNOWN","ATTESTATION_ERROR_VM_NOT_INITIALIZED","ATTESTATION_ERROR_VM_NO_RESPONSE","ATTESTATION_ERROR_VM_TIMEOUT","ATTESTATION_ERROR_VM_INTERNAL_ERROR"];g.k=Ijb.prototype;g.k.RU=nkb.FIRSTDAYOFWEEK;g.k.SU=nkb.FIRSTWEEKCUTOFFDAY;
g.k.clone=function(){var a=new Ijb(this.date);a.RU=this.RU;a.SU=this.SU;return a};
g.k.getFullYear=function(){return this.date.getFullYear()};
g.k.getYear=function(){return this.getFullYear()};
g.k.getMonth=function(){return this.date.getMonth()};
g.k.getDate=function(){return this.date.getDate()};
g.k.getTime=function(){return this.date.getTime()};
g.k.getDay=function(){return this.date.getDay()};
g.k.getUTCFullYear=function(){return this.date.getUTCFullYear()};
g.k.getUTCMonth=function(){return this.date.getUTCMonth()};
g.k.getUTCDate=function(){return this.date.getUTCDate()};
g.k.getUTCDay=function(){return this.date.getDay()};
g.k.getUTCHours=function(){return this.date.getUTCHours()};
g.k.getUTCMinutes=function(){return this.date.getUTCMinutes()};
g.k.getTimezoneOffset=function(){return this.date.getTimezoneOffset()};
g.k.set=function(a){this.date=new Date(a.getFullYear(),a.getMonth(),a.getDate())};
g.k.setFullYear=function(a){this.date.setFullYear(a)};
g.k.setYear=function(a){this.setFullYear(a)};
g.k.setMonth=function(a){this.date.setMonth(a)};
g.k.setDate=function(a){this.date.setDate(a)};
g.k.setTime=function(a){this.date.setTime(a)};
g.k.setUTCFullYear=function(a){this.date.setUTCFullYear(a)};
g.k.setUTCMonth=function(a){this.date.setUTCMonth(a)};
g.k.setUTCDate=function(a){this.date.setUTCDate(a)};
g.k.add=function(a){if(a.years||a.months){var b=this.getMonth()+a.months+12*a.years,c=this.getYear()+Math.floor(b/12);b%=12;0>b&&(b+=12);a:{switch(b){case 1:var d=0!=c%4||0==c%100&&0!=c%400?28:29;break a;case 5:case 8:case 10:case 3:d=30;break a}d=31}d=Math.min(d,this.getDate());this.setDate(1);this.setFullYear(c);this.setMonth(b);this.setDate(d)}a.days&&(c=this.getYear(),b=0<=c&&99>=c?-1900:0,a=new Date((new Date(c,this.getMonth(),this.getDate(),12)).getTime()+864E5*a.days),this.setDate(1),this.setFullYear(a.getFullYear()+
b),this.setMonth(a.getMonth()),this.setDate(a.getDate()),A6(this,a.getDate()))};
g.k.equals=function(a){return!(!a||this.getYear()!=a.getYear()||this.getMonth()!=a.getMonth()||this.getDate()!=a.getDate())};
g.k.toString=function(){var a=this.getFullYear(),b=0>a?"-":1E4<=a?"+":"";return[b+Ejb(Math.abs(a),b?6:4),Ejb(this.getMonth()+1,2),Ejb(this.getDate(),2)].join("")+""};
g.k.valueOf=function(){return this.date.valueOf()};var okb=new g.zs("addUpcomingEventReminderEndpoint");var pkb=new g.zs("removeUpcomingEventReminderEndpoint");var qkb=new g.zs("updateUpcomingEventReminderButtonStateCommand");var Ljb=new g.zs("upcomingEventReminderButtonRenderer"),Rjb=new g.zs("upcomingEventReminderButtonStateRenderer");g.w(B6,g.aT);B6.prototype.hide=function(){this.buttonElement&&this.buttonElement.removeAttribute("aria-haspopup");g.aT.prototype.hide.call(this)};
B6.prototype.show=function(){this.buttonElement&&this.buttonElement.setAttribute("aria-haspopup","true");g.aT.prototype.show.call(this)};
B6.prototype.xa=function(){g.sb(this.j);g.aT.prototype.xa.call(this)};g.w(C6,g.X);
C6.prototype.D=function(){if(this.toggleButtonRenderer){var a=this.toggleButtonRenderer;a.isToggled?this.B(a.toggledServiceEndpoint):this.B(a.defaultServiceEndpoint);a.isToggled=!a.isToggled;D6(this)}else if(this.upcomingEventReminderButtonRenderer)if(this.j&&this.j.Gb)this.j.Mb();else{var b=Ojb(this);b&&this.B(b.serviceEndpoint||b.command);b=(null==(a=g.S(null==b?void 0:b.command,g.WQ))?void 0:a.commands)||[];a:{a=g.u(b);for(var c=a.next();!c.done;c=a.next()){var d=b=void 0;if(c=null==(b=g.S(c.value,
g.icb))?void 0:null==(d=b.popup)?void 0:d.menuPopupRenderer){a=c;break a}}a=void 0}this.j||(this.j=new B6(this.I,this.buttonElement),this.j.Ja(this.element),g.H(this,this.j),this.j.subscribe("reminderMenuItemClicked",this.B,this));b=this.j;b.menuPopupRenderer=a;Kjb(b)}};
C6.prototype.B=function(a){var b=g.S(a,okb),c=g.S(a,pkb);if(a&&(b||c)){if(b){var d=b;var e="notification/add_upcoming_event_reminder"}else c&&(d=c,e="notification/remove_upcoming_event_reminder");if(e&&d&&d.params)for(Qjb(this,e,d.params),a=g.u(d.commands||[]),b=a.next();!b.done;b=a.next())if((b=b.value)&&g.S(b,qkb)){this.u=g.S(b,qkb).state;D6(this);break}}};g.w(Sjb,g.X);g.k=Sjb.prototype;g.k.getPlayerType=function(){if(8===this.api.getPresentingPlayerType())return 1};
g.k.getVideoData=function(){return this.api.getVideoData(this.getPlayerType())};
g.k.Sa=function(a){var b,c,d=null==a?void 0:null==(b=a.liveStreamability)?void 0:null==(c=b.liveStreamabilityRenderer)?void 0:c.offlineSlate;if(d){this.u=a;b=d.liveStreamOfflineSlateRenderer;b.canShowCountdown?this.YZ():Tjb(this,b);var e,f,h,l;if(c=null==a?void 0:null==(e=a.liveStreamability)?void 0:null==(f=e.liveStreamabilityRenderer)?void 0:null==(h=f.offlineSlate)?void 0:null==(l=h.liveStreamOfflineSlateRenderer)?void 0:l.thumbnail){e=0;f=null;h=c.thumbnails;for(l=0;l<h.length;l++)h[l].width>
e&&(e=h[l].width||0,f=h[l].url);f&&(this.background.style.backgroundImage="url("+f+")")}else this.background.style.backgroundImage="";b.actionButtons||b.reminderButton?(this.j||(this.j=new C6(this.api),this.j.Ja(this.Ha("ytp-offline-slate-buttons")),g.H(this,this.j)),Mjb(this.j,b.actionButtons&&b.actionButtons[0],b.reminderButton)):this.j&&Mjb(this.j,null,null);this.u=a}else this.u=null;this.b_()};
g.k.b_=function(a){if(8===this.api.getPresentingPlayerType())var b=!0;else{var c=this.api.Nb(),d=this.getVideoData();b=d.isLivePlayback&&(g.fQ(c)||g.zP(c,2)||g.zP(c,64));var e=2===d.autonavState&&g.zP(c,2);c=c.ud()&&!g.EO(d)&&!this.api.isAtLiveHead(void 0,!0);b=b&&!c&&!e}b&&this.u?this.Gb?(null==a?0:g.HP(a,2))&&!this.getVideoData().Ml&&(g.Nq(this.element,"ytp-offline-slate-collapsed"),this.C.stop(),g.Nq(this.B,"ytp-offline-slate-bar-fade"),this.D.start()):(this.show(),this.C.start(),this.api.ra("offlineslatestatechange"),
this.J&&this.api.xA()):this.Gb&&(this.hide(),this.api.ra("offlineslatestatechange"))};
g.k.YZ=function(){var a,b,c,d,e=null==(a=this.u)?void 0:null==(b=a.liveStreamability)?void 0:null==(c=b.liveStreamabilityRenderer)?void 0:null==(d=c.offlineSlate)?void 0:d.liveStreamOfflineSlateRenderer;e&&(a=Math.floor(g.eb()/1E3),b=e.canShowCountdown&&Number(e.scheduledStartTime),!b||b<=a?(Tjb(this,e),this.countdownTimer.stop()):(Tjb(this,e,g.IR(b-a)),g.Eq(this.countdownTimer)))};
g.k.xa=function(){this.countdownTimer.dispose();this.countdownTimer=null;g.X.prototype.xa.call(this)};E6.prototype.u=function(a){return this.trigger&&a.trigger?this.module===a.module&&this.trigger===a.trigger&&this.j===a.j:!1};
E6.prototype.isExpired=function(){return 6E4<(0,g.gC)()-this.B};
E6.prototype.toString=function(){return this.module+":"+this.trigger+":"+this.j};g.w(akb,g.XT);g.k=akb.prototype;g.k.xa=function(){I6(this);this.player.Te("heartbeat");g.XT.prototype.xa.call(this)};
g.k.onCueRangeEnter=function(){this.K=!0;G6(this,2E3)};
g.k.ID=function(a){this.heartbeatParams=a;G6(this,2E3)};
g.k.C0=function(a){var b;8!==this.player.getPresentingPlayerType()&&"UNPLAYABLE"!==(null==(b=this.j)?void 0:b.status)&&(g.zP(a.state,2)||g.zP(a.state,64)?(I6(this),this.C&&(this.K=!0,G6(this,1E3))):(g.zP(a.state,1)||g.zP(a.state,8))&&G6(this,2E3))};
g.k.D0=function(){3!==this.player.getPresentingPlayerType()&&G6(this,2E3)};
g.k.getPlayerType=function(){if(8===this.player.getPresentingPlayerType())return 1};
g.k.getVideoData=function(){return this.player.getVideoData(this.getPlayerType())};
g.k.ul=function(a){switch(a){case 4:case 3:return!1}return!0};
g.k.DH=function(a,b,c){a={trigger:a,reason:b};c&&(a.serializedServerContext=c.additionalLoggingData);g.OB("heartbeatActionPlayerTransitioned",a)};
g.k.Mf=function(a){var b="LICENSE",c=dkb(a);if(c)return c.reason||g.tU[b]||"";(a=a.match(ekb))&&(a=Number(a[1]))&&(b=g.CBa(a));return g.tU[b]||""};
g.k.fD=function(){return!!this.offlineSlate&&this.offlineSlate.Gb};
var ekb=/^GLS\/1.0 (\d+) (\w+).*?\r\n\r\n([\S\s]*)$/;g.WT("heartbeat",akb);})(_yt_player);
